version: '3.8'
services:
  api:
    container_name: oxygen-users-api
    build:
      context: ./
      target: production
    image: oxygen-users-api
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    volumes:
      - './:/src'
volumes:
  db:
    driver: local